name: type-check 

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 16 
      - run: npm ci
      - run: npm run type-check 
